### ISSUE TITLE
[BUG][DEPLOY] Unable to cleanup Klusterlet CRD

### ISSUE THREAD

**Issue by minsikl** [stolostron/deploy#179]
**Describe the bug**

After the execution of clean-clusters.sh, klusterlets.operator.open-cluster-management.io has still existed.

**To Reproduce**
1. Execute clean-clusters.sh
2. Generate an import code and execute it on the target cluster.

**Expected behavior**
The cluster is successfully imported. 

**Screenshots**
```
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "klusterlets.operator.open-cluster-management.io" already exists
The cluster cannot be imported because its Klusterlet CRD already exists.
Either the cluster was already imported, or it was not detached completely during a previous detach process.
Detach the existing cluster before trying the import again.%
```

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: safari

**Additional context**

**Comment by yylin1** [comment]
I meet the same issue, through using `oc replace -f original-klusterlet.yaml` can solve the problem by @wdrdres3qew5ts21.
